---
## COMMON
selinux_enabled: true
selinux_mode: permissive

## GITLAB_RUNNER
domain_company: enciso.website

## FIREWALL
firewalld_disabled: False
firewalld_rules:
      ssh:
        port: 22
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
